Home page and profile page
YigitTilki/mdp2 pull request #2
Opened 2024-11-12 16:36 UTC by YigitTilki

2024-11-13 07:24 UTC, akguleren requested changes

2024-11-13 07:24 UTC, akguleren commented on .env
.env uzantılı dosyaları .gitignore dosyası altına ekleyelim. Böyle push atıldığı zaman bir önemi kalmıyor env olmasının 😄

2024-11-13 07:24 UTC, akguleren commented on assets/i18n/en.json
Keyleri sayfa veya modül bazlı gruplandırmak yararlı olabiliyor. Proje başında kendine bir kategorizasyon yöntemi belirleyip onunla devam etmen daha iyi olur

2024-11-13 07:24 UTC, akguleren commented on ios/Runner.xcworkspace/contents.xcworkspacedata
By tür dosyaları da push atmana gerek yok. Hangi dosyaların gerekli olduğunu araştırıp gereksiz olanları gitignore dosyasına eklersin.

2024-11-13 07:24 UTC, akguleren commented on lib/feature/home/application/home_provider.dart
> +    final data = await HomeRepository().getUsers();
Servis statelerini manuel olarak yönetmişsin. Bunları provider ile tanımlamak bu yükü senin üzerinden alıyor. Şu anlık bir sorun yaşamazsın ama proje büyüdükçe bu değişkenleri ayrı ayrı yönetmek sıkıntı çıkartır. O yüzden bunları providerdan alabileceğin bir yapı araştırıp onunla güncellemeni tavsiye ederim. Viewmodelin StateNotifierProvider olmasında bir sorun yok. Sadece servislerin de provider olarak tanımlanması gerekir. En iyi provider seçeneğine de araştırarak karar verirsin.

2024-11-13 07:24 UTC, akguleren commented on lib/feature/home/data/home_repository.dart
> +class HomeRepository {
Repository yaklaşımına pek hakim değilim fakat _dio ve _logger gibi değişkenleri dışarıdan parametre olarak geçirmek bu classın bağımlılığını azaltır (Dependency Injection). Bu yapıyı entegre etmen ilerde bu classı tam olarak test edebilmeni sağlar.

2024-11-13 07:24 UTC, akguleren commented on lib/feature/home/domain/user_model/address_model.dart
> +class Address extends Equatable {
toJson ve fromJson methodları için generation paketleri kullanabilirsin işini kolaylaştırır. build_runner ve json_serializable paketlerine bakabilirsin.

2024-11-13 07:24 UTC, akguleren commented on lib/feature/home/presentation/home_view.dart
> +        title: const Text("FlutterI18n.translate(context, 'hello')"),
Burası hatalı olmuş sanırım
`title: FlutterI18n.translate(context, 'hello')`

2024-11-13 07:24 UTC, akguleren commented on lib/feature/profile/application/profile_provider.dart
> +      final data = await ProfileRepository().getUserAlbumsWithPhotos(userId);
Viewmodelin içine tüm repositorylerini late ile tanımlayıp bu değerleri viewmodel oluşurken set edersen daha faydalı olur. Şu an kurguladığın yapıda her seferinde ProfileRepository objesinden bir tane daha oluşturuyorsun. Bu da fazladan memory kullanımına sebep oluyor.

2024-11-13 07:24 UTC, akguleren commented on lib/feature/profile/presentation/profile_view.dart
> +                          label: 'gönderi',
Bunları da localize edebilirsin

2024-11-13 07:24 UTC, akguleren commented on lib/main.dart
> +  final _appRouter = AppRouter();
appRouter objesinin globale çekersen context.router diye çağırmak zorunda kalmazsın. Bazı yerlerde contexte erişmek zor oluyor

2024-11-13 07:24 UTC, akguleren commented on lib/product/init/application_init.dart
> +  static Future<void> _initialize() async {
static methodu private olarak tanımlamana gerek yok

2024-11-13 10:44 UTC, YigitTilki commented on .env
Biliyorum aslında öyle olması gerekiyor fakat bi an siz clone atarsanız diye düşündüm 😁

2024-11-13 14:56 UTC, YigitTilki commented
dediklerinizi elimden geldiğince yapmaya çalıştım. Yine yanlış yaptığım yerler olabilir teşekkürler iyi akşamlar.

2024-11-14 13:49 UTC, akguleren approved these changes

2024-11-14 13:49 UTC, merged